#!/usr/bin/env bash

# Dump current context state to .gsd/STATE.md for recovery and session continuity.
# Usage: bash scripts/dump_state.sh [--task "description"] [--attempts "list"] [--hypothesis "text"]

set -o errexit
set -o nounset
set -o pipefail

STATE_FILE=".gsd/STATE.md"
TASK="${TASK:-unknown}"
ATTEMPTS="${ATTEMPTS:-none recorded}"
HYPOTHESIS="${HYPOTHESIS:-none}"
RECOMMENDATION="${RECOMMENDATION:-Review approach and consider fresh session}"

for arg in "$@"; do
    case "$arg" in
        --task=*)       TASK="${arg#*=}" ;;
        --attempts=*)   ATTEMPTS="${arg#*=}" ;;
        --hypothesis=*) HYPOTHESIS="${arg#*=}" ;;
        --recommend=*)  RECOMMENDATION="${arg#*=}" ;;
    esac
done

mkdir -p "$(dirname "$STATE_FILE")"

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
GIT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
MODIFIED_FILES=$(git diff --name-only 2>/dev/null | head -20 || echo "none")
STAGED_FILES=$(git diff --cached --name-only 2>/dev/null | head -20 || echo "none")

cat > "$STATE_FILE" <<EOF
# Context State Dump

> Generated: ${TIMESTAMP}

## Session Info

- **Branch:** ${GIT_BRANCH}
- **Commit:** ${GIT_HASH}
- **Timestamp:** ${TIMESTAMP}

## Current Task

${TASK}

## Attempts

${ATTEMPTS}

## Hypotheses

${HYPOTHESIS}

## Modified Files (unstaged)

\`\`\`
${MODIFIED_FILES}
\`\`\`

## Staged Files

\`\`\`
${STAGED_FILES}
\`\`\`

## Recommendation

${RECOMMENDATION}

---

*This state dump was generated by context-health-monitor. Use it to resume work in a fresh session.*
EOF

echo "State dumped to ${STATE_FILE}"
echo "  Branch: ${GIT_BRANCH} @ ${GIT_HASH}"
echo "  Timestamp: ${TIMESTAMP}"
